#!/usr/bin/env bash
# SeaweedFS 存储部署配置 — 安装前请按环境修改

# 本机 IP（volume / master 绑定地址，多节点时每台机器填各自 IP）
STORAGE_NODE_IP="${STORAGE_NODE_IP:-0.0.0.0}"

# Master 集群 peers（逗号分隔 host:port）
STORAGE_MASTER_PEERS="${STORAGE_MASTER_PEERS:-0.0.0.0:7200}"

# 数据根目录
STORAGE_DATA_ROOT="${STORAGE_DATA_ROOT:-/data/server/s3}"

# 本节点启用的组件（逗号分隔）: master,volume,filer,s3,wrapper
STORAGE_COMPONENTS="${STORAGE_COMPONENTS:-master,volume,filer,s3}"

# 镜像
STORAGE_SEAWEEDFS_IMAGE="${STORAGE_SEAWEEDFS_IMAGE:-registry-public.lenovo.com/newapi/new-api:seaweedfs430}"
STORAGE_WRAPPER_IMAGE="${STORAGE_WRAPPER_IMAGE:-registry-public.lenovo.com/earth_system/seaweedfs-wrapper:3.71}"

# Volume
STORAGE_VOLUME_MAX="${STORAGE_VOLUME_MAX:-1536}"
STORAGE_VOLUME_DATA_CENTER="${STORAGE_VOLUME_DATA_CENTER:-xclaw1}"
STORAGE_VOLUME_RACK="${STORAGE_VOLUME_RACK:-rack1}"
STORAGE_VOLUME_SIZE_LIMIT_MB="${STORAGE_VOLUME_SIZE_LIMIT_MB:-4096}"
STORAGE_DEFAULT_REPLICATION="${STORAGE_DEFAULT_REPLICATION:-000}"

# 端口
STORAGE_MASTER_PORT="${STORAGE_MASTER_PORT:-7200}"
STORAGE_VOLUME_PORT="${STORAGE_VOLUME_PORT:-7201}"
STORAGE_FILER_PORT="${STORAGE_FILER_PORT:-7202}"
STORAGE_S3_PORT="${STORAGE_S3_PORT:-7203}"
STORAGE_WRAPPER_PORT="${STORAGE_WRAPPER_PORT:-7206}"

# JWT / Wrapper
STORAGE_JWT_FILER_KEY="${STORAGE_JWT_FILER_KEY:-usdzH0H13YTrZncF}"
STORAGE_WRAPPER_SECRET_KEY="${STORAGE_WRAPPER_SECRET_KEY:-usdzH0H13YTrZncF}"

# S3 访问密钥（config.json；经 install.sh 部署时以 install.config.sh 为准）
STORAGE_S3_ACCESS_KEY="${STORAGE_S3_ACCESS_KEY:-admin}"
STORAGE_S3_SECRET_KEY="${STORAGE_S3_SECRET_KEY:-ChangeMeS3SecretKey}"

# gRPC mTLS（security.toml）：无证书时 install.sh 可自动生成自签名证书
STORAGE_GRPC_TLS_AUTO_CERT="${STORAGE_GRPC_TLS_AUTO_CERT:-true}"
# 设为 true 强制重新生成（修复 handshake failed 时可用）
STORAGE_GRPC_TLS_REGENERATE="${STORAGE_GRPC_TLS_REGENERATE:-false}"
