[filer.options]
recursive_delete = false
max_file_name_length = 512

[redis2_sentinel]
enabled = true
addresses = __REDIS_SENTINEL_ADDRS_JSON__
masterName = "__REDIS_SENTINEL_MASTER__"
username = ""
password = "__REDIS_PASSWORD__"
